---
deployment:
  tasks:
    - export DEPLOYPATH=/home/littlefx/public_html/little-f-angular/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R products $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH